FROM registry.access.redhat.com/ubi9-minimal:9.8 AS builder

RUN microdnf install -y golang git make tar gzip && microdnf clean all

# Install Go 1.26.3 (required by go.mod)
RUN curl -fsSL -o /tmp/go.tgz https://go.dev/dl/go1.26.3.linux-s390x.tar.gz && \
    rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go.tgz && rm /tmp/go.tgz

ENV PATH=/usr/local/go/bin:$PATH
ENV GOARCH=s390x
ENV GOOS=linux
ENV GOTOOLCHAIN=local

WORKDIR /go/src/github.com/openshift/cluster-resource-override-admission-operator
COPY . .

RUN GOFLAGS=-mod=vendor go build -o bin/cluster-resource-override-admission-operator \
    ./cmd/cluster-resource-override-admission-operator/...

FROM registry.access.redhat.com/ubi9-minimal:9.8
COPY --from=builder /go/src/github.com/openshift/cluster-resource-override-admission-operator/bin/cluster-resource-override-admission-operator /usr/bin/
