FROM registry.access.redhat.com/ubi9/go-toolset:1.22 AS builder
USER root
WORKDIR /go/src/github.com/openshift/cluster-resource-override-admission-operator
COPY . .
RUN GOARCH=s390x GOOS=linux GOFLAGS=-mod=vendor make build

FROM registry.access.redhat.com/ubi9-minimal:9.8
COPY --from=builder /go/src/github.com/openshift/cluster-resource-override-admission-operator/bin/cluster-resource-override-admission-operator /usr/bin/
